export const SET_WEB3 = 'SET_WEB3';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_CONTRACT = 'SET_CONTRACT';
export const SET_STORAGE_VALUE = 'SET_STORAGE_VALUE';
export const INCREMENT_STORAGE_VALUE = 'INCREMENT_STORAGE_VALUE';